### ISSUE TITLE
Example project fails to build

### ISSUE THREAD

**Issue by cjwirth** [DenHeadless/DTTableViewManager#23]
There's probably just some setting that I'm forgetting to set, but it would be pretty ideal if you could just pull and run. 

Here's how I got/started the project:
```
caesar at macbook in ~/Developer/scratch
○ git clone git@github.com:DenHeadless/DTTableViewManager.git
Cloning into 'DTTableViewManager'...
remote: Counting objects: 4106, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4106 (delta 0), reused 0 (delta 0), pack-reused 4100
Receiving objects: 100% (4106/4106), 1.67 MiB | 1.25 MiB/s, done.
Resolving deltas: 100% (2580/2580), done.
Checking connectivity... done.

caesar at macbook in ~/Developer/scratch
○ cd DTTableViewManager/Example                         09/16/2015 10:57:53 JST

caesar at macbook in ~/Developer/scratch/DTTableViewManager/Example on master
☿ pod install                                           09/16/2015 10:58:23 JST
Updating local specs repositories

CocoaPods 0.39.0.beta.4 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Cedar (0.11.3)
Installing DTModelStorage (1.2.4)
Installing OCMock (2.2.4)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `DTTableViewManager.xcworkspace` for this project from now on.
Sending stats

caesar at macbook in ~/Developer/scratch/DTTableViewManager/Example on master!
☿ open DTTableViewManager.xcworkspace                   09/16/2015 10:58:39 JST
```

Then build the Example target, and [SectionModel+HeaderFooter.swift](https://github.com/DenHeadless/DTTableViewManager/blob/master/DTTableViewManager/Utilities/SectionModel%2BHeaderFooter.swift#L27) is telling me "No such module 'DTModelStorage'"

Just thought I'd let you know. :)

**Comment by cjwirth** [comment]
I noticed that it's including [DTModelStorage](https://github.com/DenHeadless/DTModelStorage) through carthage. So I ran `carthage update` in the main directory. It failed to build.

The problem was with the Development Team set in the Xcode project. It is set to your Team ID, so I changed it to "None," and was able to complete the build in carthage.

However, I'm still getting a [lot of errors](https://gist.github.com/anonymous/a9d2f163b216d17d5c1e) when building the DTTableViewManager example project. Something wrong when linking to DTModelStorage.

**Comment by DenHeadless** [comment]
Hi! 
Thanks for reporting and sorry about that! I forgot to remove previous CocoaPods integration from framework, it's no longer used right now. You need to use XCode 7 and XCode 7 command line tools when running `carthage update`.

I've updated readme section with [better instructions](https://github.com/DenHeadless/DTTableViewManager/blob/master/README.md#running-example-project) on how to run example project. 

Again, sorry about that, if something doesn't work, please let me know!

**Comment by cjwirth** [comment]
Hey thanks for the quick update. Unfortunately, there's still a problem. 

Clone and run Carthage:

```
caesar at macbook in ~/Developer/scratch
○ git clone git@github.com:DenHeadless/DTTableViewManager.git
Cloning into 'DTTableViewManager'...
remote: Counting objects: 4112, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 4112 (delta 3), reused 0 (delta 0), pack-reused 4100
Receiving objects: 100% (4112/4112), 1.68 MiB | 280.00 KiB/s, done.
Resolving deltas: 100% (2583/2583), done.
Checking connectivity... done.

caesar at macbook in ~/Developer/scratch
○ cd DTTableViewManager                                 09/16/2015 17:27:30 JST

caesar at macbook in ~/Developer/scratch/DTTableViewManager on master
☿ carthage update                                       09/16/2015 17:27:35 JST
*** Fetching DTModelStorage
*** Fetching Nimble
*** Checking out DTModelStorage at "2.0.0"
*** Checking out Nimble at "a87c41424b2b8bc7821cf9e0352f87f53daf5263"
*** xcodebuild output can be found in /var/folders/fk/qzkyj9h52yn0zw3p7_fdy391t_zybt/T/carthage-xcodebuild.c7rFC5.log
*** Building scheme "DTModelStorage" in DTModelStorage.xcodeproj
** BUILD FAILED **


The following build commands failed:
        Check dependencies
(1 failure)
```
Build log: https://gist.github.com/cjwirth/5e38e23bd822e527ed0d

> Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “L94VC9ZZXC” were found.

So I went into the DTModelStorage, and removed the Development Team from the project over there:

```
caesar at macbook in ~/Developer/scratch/DTTableViewManager on master
☿ open Carthage/Checkouts/DTModelStorage/DTModelStorageTests/DTModelStorage.xcodeproj

/// Delete the Team ID from the project in Xcode ///

caesar at macbook in ~/Developer/scratch/DTTableViewManager on master
☿ carthage build                                        09/16/2015 17:31:27 JST
*** xcodebuild output can be found in /var/folders/fk/qzkyj9h52yn0zw3p7_fdy391t_zybt/T/carthage-xcodebuild.a8Ce4T.log
*** Building scheme "DTModelStorage" in DTModelStorage.xcodeproj
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Nimble-OSX" in Nimble.xcodeproj
```

After doing this, running the DTTableViewManager sample project worked.

**Comment by DenHeadless** [comment]
Yep, codesigning failed me again =) I removed explicit development team from DTModelStorage, and added 2.0.1 tag to that commit. Hopefully now everything should work fine.

**Comment by cjwirth** [comment]
Awesome, worked great this time, thanks!
